apiVersion: apps/v1
kind: Deployment
metadata:
  name: assessment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assessment-service
  template:
    metadata:
      labels:
        app: assessment-service
    spec:
      containers:
      - name: assessment
        image: assessment-service:latest
        ports:
        - containerPort: 8080
